{{- if .Values.pvc.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name | default (printf "%s-pvc" .Values.name) }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.pvc.accessModes | default "ReadWriteOnce" | quote }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage | default "1Gi" | quote }}
  {{- if .Values.pvc.storageClassName.name }}
  storageClassName: {{ .Values.pvc.storageClassName.name }}
  {{- end }}
{{- end }}